---
nav:
  title: Node
  order: 5
title: 07. Promise 其他方法的实现
order: 7
---

# Promise 其他方法的实现

9.other.js

```js
let Promise= require('./promise')
const fs = require('fs')

// function readFile(...args) {
//   return new Promise((resolve, reject) => {
//     fs.readFile(...args, function (err, data) {
//       if (err) return reject(err);
//       resolve(data);
//     })
//   })
// }

// 上面代码替换为
// 1. 延迟对象来解决嵌套问题
// Q 这个库是这样使用的
function readFile(...args) {
  let dfd = Promise.deferred()
  fs.readFile(...args, function (err, data) {
    if (err) return dfd.reject(err)
    dfd.resolve(data)
  })
  return dfd.promise
}

readFile('./a.txt', 'utf8').then(data => {
  console.log(data);
}).catch(err => {
  console.log(err)
})  // catch 后面可以继续调用 then 方法


// 原型的方法是公共的通过实例来调用的。静态方法是放在类上调用的

// 静态方法 Promise.resolve() Promise.reject()
// 差异在 resolve 方法它具备等待效果
Promise.resolve('hello').then(data => {
  console.log(data);
})
Promise.reject('hello').catch(err => {
  console.log(err)
})
```

promise/2.index.js

```js
// promise/2.index.js

const PENDING = "PENDING"; // 默认等待态
const FULFILLED = "FULFILLED";  // 成功态
const REJECT = "REJECT";  // 失败态

function resolvePromise(x, promise2, resolve, reject) { // 我们还需要考虑 x 可能是别人家的 promise
                                                        // 希望我的 promise 可以和别人的 promise 一起来混用的 q库 bluebird库

  // If promise and x refer to the same object, reject promise with a TypeError as the reason.
  if (x === promise2) {
    // 为什么要报这个错误？ promise2 会一直处于 pending 状态，就卡死了。
    return reject(new TypeError('循环引用'))
  }

  // 继续判断 x 是不是一个 promise, promise 需要有 then 方法(啥时候是函数的？别人写的 promise 就有可能是函数)
  if ((typeof x === 'object' && x !== null) || (typeof x === 'function')) {
    // 才有可能是一个 promise，继续判断 x 是否有then
    let called
    try {
      let then = x.then  // 尝试取 then 方法
      if (typeof then === 'function') { // 我就认为他是 promise 了
        // x.then   // 这个会再次取一次属性，触发 get 方法
        // then.call(x) // 这个不会
        then.call(x, (y) => { // y 有可能还是一个 promise, 所以要再次进行解析流程
          if (called) return
          called = true
          // 需要不停的解析成功的 promise 中返回的成功值，直到这个值是一个普通值
          resolvePromise(y, promise2, resolve, reject)
        }, (r) => {
          if (called) return
          called = true
          reject(r)
        })
      } else {
        if (called) return;
        called = true;
        resolve(x)
      }
    } catch(e) {
      if (called) return
      called = true
      reject(e)
    }
  } else {
    // x 是一个普通值
    resolve(x)
  }

  // 如果x是一个普通值则直接调用resolve即可

  // 如果x是一个promise那么应该采用这个promise的状态决定调用的是resolve还是reject
}

class Promise {
  constructor(executor) { // executor 会默认执行 同步执行
    this.status = PENDING
    this.value = undefined
    this.reason = undefined

    this.onResolvedCallbacks = []
    this.onRejectedCallbacks = []
    // 用户调用 resolve 和 reject 可以将对应的结果暴露在当前的 promise 实例上
    const resolve = (value) => {
      if (value instanceof Promise) { // 这个方法并不属于 规范中的，只是为了和原生 promise 表现形式一样
        return value.then(resolve, reject) // === resolvePromise
      }

      if (this.status === PENDING) {
        this.value = value
        this.status = FULFILLED
        this.onResolvedCallbacks.forEach(fn => fn())
      }
    }

    const reject = (reason) => {
      if (this.status === PENDING) {
        this.reason = reason
        this.status = REJECT
        this.onRejectedCallbacks.forEach(fn => fn())
      }
    }

    try {
      executor(resolve, reject); // 默认 new Promise中的函数会立即执行
    } catch (e) { // 如果执行时出错，我们将错误传递到 reject 中 =》 执行到了失败逻辑
      reject(e)
    }
  }

  then(onFulfilled, onRejected) {
    onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : v => v
    onRejected = typeof onRejected === 'function' ? onRejected : e => { throw e }
    // 每次调用 then 方法，都必须返回一个全新的 promise
    let promise2 = new Promise((resolve, reject) => {
      // NOTE: x 就是上一个 then 成功或者失败的返回值，这个 x 决定 promise2 走成功还是走失败
      if (this.status === FULFILLED) {
        setTimeout(() => {
          try {
            let x = onFulfilled(this.value)
            resolvePromise(x, promise2, resolve, reject)
          } catch(e) {
            reject(e)
          }
        }, 0)
      }

      if (this.status === REJECT) {
        setTimeout(() => {
          try {
            let x = onRejected(this.reason)
            resolvePromise(x, promise2, resolve, reject)
          } catch (e) {
            reject(e)
          }
        }, 0)
      }

      if (this.status === PENDING) {
        console.log('pending')
        // 发布订阅模式
        this.onResolvedCallbacks.push(() => {
          setTimeout(() => {
            try {
              let x = onFulfilled(this.value)
              resolvePromise(x, promise2, resolve, reject)
            } catch(e) {
              reject(e)
            }
          }, 0)
        })
        this.onRejectedCallbacks.push(() => {
          setTimeout(() => {
            try {
              let x = onRejected(this.reason)
              resolvePromise(x, promise2, resolve, reject)
            } catch (e) {
              reject(e)
            }
          }, 0)
        })
      }
    })
    return promise2
  }
  catch(errFn) {
    return this.then(null, errFn)
  }
  static resolve(value) {
    return new Promise((resolve, reject) => {
      resolve(value)
    })
  }
  static reject(err) {
    return new Promise((resolve, reject) => {
      reject(err)
    })
  }
}

// 静态方法
Promise.deferred = function() {
  let dfd = {};
  dfd.promise = new Promise((resolve, reject) => {
    dfd.resolve = resolve
    dfd.reject = reject
  })
  return dfd
}

module.exports = Promise
```



15157103862